### ISSUE TITLE
Segmentation of sentences in lowercase

### ISSUE THREAD

**Issue by konstantinmiller** [tsproisl/SoMaJo#15]
Can it be that whenever a sentence is starting with a lowercase letter, it won't be recognized as a new sentence? For example, while "Das war es. Es funktioniert nicht." works fine, "Das war es. es funktioniert nicht." is returned as one sentence. Is that a bug or intended behavior?

**Comment by tsproisl** [comment]
SoMaJo uses a fairly simple rule-based sentence splitter. Currently, the sentence splitter assumes that sentences start with an uppercase letter or a digit (optionally preceded by things like quotation marks, etc.), unless the sentence boundary is due to a paragraph boundary or an XML tag. There are of course cases where this is not ideal. If you're feeling adventurous, you can go to line 250 of `sentence_splitter.py` and change the line from
````python
if tok_j.text[0].isupper() or tok_j.text.isnumeric():
````
to
````python
if tok_j.text.isalnum():
````
This will increase recall at the cost of lower precision. I have no idea by how much. If the trade-off is acceptable, we could make case sensitivity configurable. I should probably run some experiments, if I find the time…

**Comment by konstantinmiller** [comment]
I see. Thanks for the information. Will play around with that.
