### ISSUE TITLE
Problem with a technical term and splitting by hyphen

### ISSUE THREAD

**Issue by g3rfx** [tsproisl/SoMaJo#32]
Hi, 

I noticed that the English tokenizer splits the term "3G" into "3" and "G", while it should not. Also, I wonder whether "time-varying" and "location-dependent" should have been split by the hyphens, as it semantically makes sense for them not to be split.

Working example:

```
from somajo import SoMaJo
paragraphs = ["Third Generation (3G) cellular networks take advantage of time-varying and location-dependent channel conditions of mobile users to provide broadband services."]
tokenizer = SoMaJo(language="en_PTB")
sentences = tokenizer.tokenize_text(paragraphs)
for sentence in sentences:
    for token in sentence:
        print(token.text)
```

Output:
```
Third
Generation
(
3
G
)
cellular
networks
take
advantage
of
time
-
varying
and
location
-
dependent
channel
conditions
of
mobile
users
to
provide
broadband
services
.
```

**Comment by tsproisl** [comment]
Hi,

the treatment of “time-varying” and “location-dependent” is in accordance with the tokenization guidelines [(Mott et al., 2009: 4)](https://web.archive.org/web/20110727133755/http://projects.ldc.upenn.edu/gale/task_specifications/ettb_guidelines.pdf).

“3G” was split into “3” and “G” because the “G” was interpreted as a unit of measurement. For resolving the issue I assumed that the network technology occurs more frequently in the wild than mentions of small weights or great accelerations and added “3G”, “4G” and “5G” to the list of tokens that should not be split.

Version 2.4.3 includes the fix.

**Comment by g3rfx** [comment]
Oh. I didn't know about that paper and will take a look into it. Thank you.

Also, thanks for adding the fix.
